### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kjell** [artsmia/art#1]
# smaller things
- [x] forward/back don't update search `<input>`, learn react
- [x] strip input query so insignificant spaces don't needlessly search
- [ ] if I scroll down, de-activate the search box so 'space' doesn't add a space to the query, it scrolls further
- [x] include highlight of matching text in search result
  - [x] highlight more than just artist and artwork name?
- [x] loading indication
  - [x] for images
  - [x] and searching
- [x] "show all" toggle at the end of the first 100 results, or automatically load the rest?
  - [x] do the aggregation filters make sense to repeat at the bottom of the search results too?
# bigger things
- [ ] readme
- [x] "show all"
  - [x] cap show all so we don't throttle elasticsearch too hard?
- [x] lazy load search results
  - [x] when a search 'finalizes', call out to pre-warm the images on the page so when it's time to lazy load an image, it's ready ASAP. Or just make the images faster?
- [ ] 'finalize' searches, tweak fast searching behavior
  - ping elasticsearch every 200ms, but after a few seconds have passed since the last search…
    - update history / URL, change route
    - (see above) start fetching images from mediabin
    - send a search analytics event
- [x] filters: image available and on view
  - [x] aggregate a binary 'on view' or not, with individual galleries as a sub-aggregation of 'on view'
  - [x] same for `image: valid | invalid`, valid -> `public domain | zoomable but not download-able | copyrighted`
  - [x] use filters to search through aggregations, appending to the search text feels clumsy?
- [ ] search facets ala v&a spelunker (`/search/facet/image_copyright/*ARS*`, or query strings)
- [x] link object page
  - [ ] pretty `/artwork/id/title`?
- [x] render "isomorphically"
- [ ] cache intensive searches in redis (by some factor of how long they took to complete?)
  - [ ] http caching too, or cache results in localstorage?
- [x] elasticsearch suggestions or ngram index
- [ ] until the API handles 'constituents' properly, 'fake' artist pages: `/artist/<name>` -> es `artist.name:<name>`
# ideas (really big things)
- [ ] russian nesting doll search/browse?
  - ['Katayama'](http://collection.staging.artsmia.org/#/search/katayama), 2 results, one of them 'forest'
  - if I'm interested in forests, hover over the word forest for long enough and a second search view appears alongside (to the right of) the current one, with results for 'forest'.
  - or a preview of what I'd get searching for 'forest' ("197 results, 80 with an image, 20 on view" with the first few thumbnails)
- [ ] "similar objects"
